### ISSUE TITLE
How to hide read-only methods? 

### ISSUE THREAD

**Issue by ageyev** [webmass/ether-gui#1]
`
excludeMethods={[
    'decimals (uint8)',
]}
`
does not work for read-only methods. 

And using 'methods' also don't work for read only methods. This:
`
methods={[
    'decimals (uint8)',
     'transferOwnership(address)'
]}
`
will show 'transferOwnership', but not read-only 'decimals'

**Comment by webmass** [comment]
From what I see the issue is the space between `decimals` and `(uint8)`

In the `examples` folder, you can see a working example of showing / hiding methods : 
https://github.com/webmass/ether-gui/blob/main/examples/src/components/ExampleContractUI.jsx

**Comment by ageyev** [comment]
For standard ERC20 contract:
```
                           excludeMethods={[
                                'decimals()', // excluded
                                'name(string)', // not excluded
                                'allowance(address,address)', // excluded
                                'approve()', // not excluded 
                            ]}
```
Thus in read-only methods we should remove arguments.

**Comment by webmass** [comment]
> For standard ERC20 contract:
> 
> ```
>                            excludeMethods={[
>                                 'decimals()', // excluded
>                                 'name(string)', // not excluded
>                                 'allowance(address,address)', // excluded
>                                 'approve()', // not excluded 
>                             ]}
> ```
> 
> Thus in read-only methods we should remove arguments.

No, to exclude functions the principle is exactly the same between read-only functions and write functions, you just need the **correct function signature** (the function name with its parameter types), read or write they both can have inputs or not.

In a ERC20 contract, the _name_ function does not have any input, so it's just 'name()' not 'name(string)'.
_approve_ function is a function with two inputs, the correct signature is 'approve(address,uint256)' not 'approve()'

So in your example it would be : 

```javascript
excludeMethods={[
    'decimals()', // read function with 0 input
    'name()', // read function with 0 input
    'allowance(address,address)', // read function with 2 inputs
    'approve(address,uint256)', // write function with 2 inputs
]}
```

**Comment by ageyev** [comment]
@webmass thank you!
